# Generated by Django 5.2 on 2025-09-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_alter_profissional_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=11, unique=True),
        ),
    ]
