# Generated by Django 5.2 on 2025-09-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_alter_profissional_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
