# Generated by Django 5.2 on 2025-09-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0004_alter_profissional_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='comissao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
