# Generated by Django 5.2 on 2025-09-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0005_alter_profissional_comissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='registro_profissional',
            field=models.CharField(max_length=25),
        ),
    ]
