# Generated by Django 5.2 on 2025-09-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacientesCadastrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=120)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('rg', models.CharField(default=None, max_length=10, unique=True)),
                ('cpf', models.CharField(default=None, max_length=11, unique=True)),
            ],
        ),
    ]
