# Generated by Django 5.2 on 2025-08-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientescadastrados',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacientescadastrados',
            name='nome_completo',
            field=models.CharField(default='sem nome', max_length=120),
        ),
        migrations.AddField(
            model_name='pacientescadastrados',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
