# Generated by Django 5.2 on 2025-09-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_do_fim', models.TimeField()),
                ('observacoes', models.TextField()),
                ('valor_da_consulta', models.FloatField()),
                ('data_de_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
