# Generated by Django 5.2 on 2025-09-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='valor_da_consulta',
            field=models.FloatField(default=70),
        ),
    ]
