# Generated by Django 5.2 on 2025-09-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_alter_consulta_valor_da_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status_do_pagamento',
            field=models.CharField(choices=[('PAGO', 'PAGO'), ('ATRASADO', 'ATRASADO')], default='', max_length=10),
        ),
    ]
